### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by raedaf** [Dallas-Mann/Convolution#1]
hello 
im trying to run the program but i have an errors
![1](https://cloud.githubusercontent.com/assets/24498161/24753897/eb47ff88-1adc-11e7-90c6-c0cb92bc6492.png)

**Comment by raedaf** [comment]
![1](https://cloud.githubusercontent.com/assets/24498161/24753959/2521d260-1add-11e7-8749-bded2b64598c.png)

**Comment by Dallas-Mann** [comment]
Remove the import for java.awt.Image and make sure the Image.java that I wrote is in the same package as Mask.java, Operator.java, and entryPoint.java

The import for java.awt.Image is importing a default java Image class, and it just so happens that the name of my Image class is the same.

**Comment by raedaf** [comment]
thank you any advice regarding this error 
![untitled](https://cloud.githubusercontent.com/assets/24498161/24765887/2c651828-1b02-11e7-9f9e-92cc165270ce.png)

**Comment by Dallas-Mann** [comment]
You need to provide the input image, the two image mask files, and the output image name as command line arguments. Some sample masks and images are in the repo. To do sobel edge detection you would use the horizontal mask and the vertical mask.

**Comment by raedaf** [comment]
how I can provide then ?

**Comment by Dallas-Mann** [comment]
In netbeans go to Project --> Properties --> Run --> and type the arguments next to "Arguments".

The format is inputImage.png mask1.txt mask2.txt outputImage.png

For the images and masks in my repo you could use the following:

tree.png verticalEdge.txt horizontalEdge.txt output.png

this will create a new image called output.png with the image processing applied to it.

Make sure you run your project via run | run main project instead of run | run file

**Comment by raedaf** [comment]
thank you very much :)

**Comment by raedaf** [comment]
I want to make this code run in multiple thread can you give me any advice

**Comment by Dallas-Mann** [comment]
It's not as simple as just enabling multiple threads. The data structures that hold the pixel values are not thread safe, nor is the algorithm used to apply the masks to the image parallelize-able.
